name: Otomatik Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Kodları Kopyala
        uses: actions/checkout@v4

      # Eski tüm release'leri silen adım
      - name: Eski Release'leri Temizle
        run: |
          gh release delete latest --cleanup-tag --yes || echo "Henüz bir release yok."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Yeni ve temiz release oluşturma adımı
      - name: Güncel Release Oluştur
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          name: "En Son Sürüm"
          body: "Bu sürüm main branch'ine yapılan son commit ile otomatik olarak güncellenmiştir."
          artifacts: "*.exe" 
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}